on: 
  push:
    branches:
      - main

jobs:
  build-and-push-to-ecr-stage:
    runs-on: ubuntu-latest
    name: Build and push Docker image to Amazon ECR

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: mevboost
        IMAGE_TAG: ${{ github.sha }}
        DEPLOY_TAG: v1
        DOCKER_FILE: Dockerfile
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Dockerfiles/$DOCKER_FILE .
        docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$DEPLOY_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG 
        docker push $REGISTRY/$REPOSITORY:$DEPLOY_TAG
        docker rmi -f $REGISTRY/$REPOSITORY:$IMAGE_TAG
